version: 2

services:
  telempup:
    container_name: telempup
    build: .
    image: telempup:latest
    volumes:
      - podcasts:/home/app/podcasts
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PYTHONUNBUFFERED=1

volumes:
  podcasts:
    external: true
