services:
  telempup:
    build: .
    image: telempup:latest
    volumes:
      - podcasts:/home/app/podcasts
    environment:
      - BOT_TOKEN=${BOT_TOKEN}

volumes:
  podcasts:
    external: true
